"""
A single cell ATAC-seq analysis pipeline.
"""

configfile: "config.yaml"

outprefix = config["outprefix"]

import yaml
import sys
import os

sys.path.append(os.path.abspath('./..'))

from src.scATAC_utility import get_fastqlist

rule all:
    input:
        qcmap = "Result/QC/" + outprefix + "_map.pdf",
        qcfrag = "Result/QC/" + outprefix + "_frag.pdf",
        qcfrip = "Result/QC/" + outprefix + "_frip.pdf",
        analysis = "Result/Analysis/",
        count = "Result/Analysis/" + outprefix + "_binary.txt",
        genescore = "Result/Analysis/" + outprefix + "_genescore.txt",
        tfscore = "Result/Analysis/" + outprefix + "_TFscore.txt"

if config["platform"] == "microfluidic":
    rule bwa_map:
        input:
            fasta = config["genome"]["fasta"],
            fastq1 = config["fastqdir"] + "/{fastqid}_1.fastq",
            fastq2 = config["fastqdir"] + "/{fastqid}_2.fastq"
        output:
            bam = "Result/BWA/{fastqid}.sortedByPos.bam"
        params:
            cores = config["cores"]
        shell:
            "bwa mem -t {params.cores} {input.fasta} {input.fastq1} {input.fastq2} "
            "| samtools view --threads {params.cores} -b "
            "| samtools sort --threads {params.cores} -o {output.bam}"

    rule picard_rmdp:
        input:
            bam = "Result/BWA/{fastqid}.sortedByPos.bam"
        output:
            bam = "Result/BWA/{fastqid}.sortedByPos.rmdp.bam",
            metric = "Result/BWA/{fastqid}.sortedByPos.rmdp.txt"
        params:
            cores = config["cores"]
        shell:
            "picard MarkDuplicates INPUT={input.bam} OUTPUT={output.bam} METRICS_FILE={output.metric};"
            "rm {input.bam}"

    rule bam_index:
        input:
            bam = "Result/BWA/{fastqid}.sortedByPos.rmdp.bam"
        output:
            bai = "Result/BWA/{fastqid}.sortedByPos.rmdp.bam.bai"
        shell:
            "samtools index {input.bam}"

    rule bam_merge:
        input:
            bam = expand("Result/BWA/{fastqid}.sortedByPos.rmdp.bam", fastqid = get_fastqlist(config["fastqdir"]))
        params:
            cores = config["cores"],
        output:
            bam = "Result/BWA/" + outprefix + ".merged.sortedByPos.rmdp.bam"
        shell:
            "ls Result/BWA/*.sortedByPos.rmdp.bam > Result/BWA/bamlist.txt"
            "samtools merge --threads {params.cores} {output.bam} Result/BWA/*.sortedByPos.rmdp.bam"

    rule short_fragment:
        input:
            bam = "Result/BWA/" + outprefix + ".merged.sortedByPos.rmdp.bam"
        output:
            fragbed = "Result/QC/" + outprefix + "_frag.bed",
            shortsam = "Result/Analysis/" + outprefix + ".merged.sortedByPos.rmdp.50bp.sam"            
        shell:
            "mkdir Result/QC"
            "mkdir Result/Analysis"
            "samtools view {input.bam} | head -10000000 | awk '{if($9>0) print $9}' | cut -f 9 > {output.fragbed}"
            "samtools view {input.bam} | awk -F'\t' 'function abs(x){return ((x < 0.0) ? -x : x)} {if (abs($9) < 50) print $0}' > {output.shortsam}"

    rule scatac_qcstat:
        input:
            bam = "Result/BWA/{fastqid}.sortedByPos.rmdp.bam",
            promoter = "../src/annotations/" + config["species"] + "_promoter.bed"
            chrM = "../src/annotations/" + config["species"] + "_chrM.bed"
        output:
            log = "Result/Log/bamLog/{fastqid}.mapping.log",
            bed = "Result/BWA/{fastqid}.sortedByPos.rmdp.bed",
        shell:
            "mkdir Result/Log"
            "mkdir Result/Log/bamLog"
            "samtools flagstat {input.bam} > {output.log}"
            "bamToBed -i {input.bam} > {output.bed}"
            "intersectBed -wa -a {output.bed} -b {input.chrM} -u | wc -l >> {output.log};"
            "cut -f 1-3 {output.bed} | sort -k1,1 -k2,2n | uniq | grep -v 'MT' | wc -l >> {output.log};"
            "cut -f 1-3 {output.bed} | sort -k1,1 -k2,2n | uniq | grep -v 'MT' | intersectBed -wa -a - -b {input.promoter} -u | wc -l >> {output.log}"
            "rm {output.bed}"

    rule scatac_qcplot:
        input:
            log = "Result/Log/bamLog"
            fragbed = "Result/QC/" + outprefix + "_frag.bed",
        output:
            stat = "Result/QC/singlecell.txt",
            qcfrag = "Result/QC/" + outprefix + "_frag.pdf",
            qcmap = "Result/QC/" + outprefix + "_map.pdf",
            qcfrip = "Result/QC/" + outprefix + "_frip.pdf",
            validbarcode = "Result/QC/" + outprefix + "_barcodes.txt",
        params:
            platform = config["platform"],
            outdir = "Result/QC",
            outpre = outprefix
        shell:
            "python ../src/scATAC_microfluidic_qc.py {input.log} {output.stat};"
            "Rscript ../R/scATACseq_qc.R {output.stat} {input.fragbed} {params.platform} {params.outpre} {params.outdir}"

    rule all_peakcall:
        input:
            bam = "Result/BWA/" + outprefix + ".merged.sortedByPos.rmdp.bam"
        output:
            bed = "Result/Analysis/" + outprefix + "_all_peaks.narrowPeak"
        params:
            name = "Result/Analysis/" + outprefix + "_all"
        log:
            "Result/Log/" + outprefix + "_macs2_allpeak.log"
        shell:
            "macs2 callpeak -g hs -n {params.name} -B -q 0.05 --nomodel --extsize=50 --SPMR -t {input.bam}"
    
    rule short_peakcall:
        input:
            sam = "Result/Analysis/" + outprefix + ".merged.sortedByPos.rmdp.50bp.sam"            
        output:
            bed = "Result/Analysis/" + outprefix + "_50bp_peaks.narrowPeak"
        params:
            name = "Result/Analysis/" + outprefix + "_50bp"
        log:
            "Result/Log/" + outprefix + "_macs2_shortpeak.log"
        shell:
            "macs2 callpeak -g hs -n {params.name} -B -q 0.05 --nomodel --extsize=50 --SPMR -t {input.sam}"
    
    if config["custompeaks"]
        rule merge_peak:
            input:
                allpeak = "Result/Analysis/" + outprefix + "_all_peaks.narrowPeak"
                shortpeak = "Result/Analysis/" + outrefix + "_50bp_peaks.narrowPeak"
                custompeak = config["custompeaksloc"]
            output:
                custompeaksort = "Result/Analysis/" + outprefix + "_custom_peaks.bed"
                finalpeak = "Result/Analysis/" + outprefix + "_final_peaks.bed"
            shell:
                "sort -k1,1 -k2,2n {input.custompeak} > {output.custompeaksort}"
                "mergeBed -i {input.allpeak} {input.shortpeak} {output.custompeaksort} | grep -v '_' | grep -v 'chrEBV' > {output.mergepeak} "
    else:
        rule merge_peak:
            input:
                allpeak = "Result/Analysis/" + outprefix + "_all_peaks.narrowPeak"
                shortpeak = "Result/Analysis/" + outrefix + "_50bp_peaks.narrowPeak"
           output:
                finalpeak = "Result/Analysis/" + outprefix + "_final_peaks.bed"
            shell:
                "mergeBed -i {input.allpeak} {input.shortpeak} | grep -v '_' | grep -v 'chrEBV' > {output.mergepeak} "
 
    rule count_peak:
        input:
            finalpeak = "Result/Analysis/" + outprefix + "_final_peaks.bed"
            validbarcode = "Result/QC/" + outprefix + "_barcodes.txt",
        output:
            count = "Result/Analysis/" + outprefix + "_binary.txt"
        params:
            cores = config["cores"]
        shell:
            "python ../src/scATAC_microfluidic_count.py {input.finalpeak} {input.validbarcode} {output.count} {params.cores}"

    rule scatac_clustering:
        input:
            count = "Result/Peak/" + outprefix + "_binary.txt"
        output:
            directory("Result/Analysis")
        params:
            outpre = outprefix,
            species = config["species"],
        shell:
            "Rscript ../R/scATACseq_pipe.R {input.count} {params.species} {params.outpre} {output}"

    rule scatac_genescore:
        input:
            count = "Result/Analysis/" + outprefix + "_binary.txt"
        output:
            genescore = "Result/Analysis/" + outprefix + "_genescore.txt"
        params:
            genedistance = config["genedistance"]
            genebed = "../src/annotations/" + config["species"] +"_ensembl.bed"
            cores = config["cores"]
        shell:
            python ../src/scATAC_genescore.py {input.count} {output.genescore} {params.genedistance} {params.genebed} {params.cores}

    rule scatac_tfscore:
        input:
            count = "Result/Analysis/" + outprefix + "_binary.txt"
        output:
            tfscore = "Result/Analysis/" + outprefix + "_tfscore.txt"
        params:
            gcbed = "../src/annotations/" + config["species"] + "_window_1kb.bed",
            tfindex = "../src/annotations/" + config["species"] + "_tf_peak_loct_1kb.h5",
            tfpercent = config["tfpercent"]
            cores = config["cores"]
        shell:
            "python ../src/scATAC_TFscore.py {input.count} {output.tfcore} {params.gcbed} {params.tfindex} {params.tfpercent} {params.cores}"

else:
    if config["platform"] == "sci-ATAC-seq":
        rule barcode_preprocess:
            input:
                fastq1 = config["fastqdir"] + "/{fastqid}_1.fastq"
                fastq2 = config["fastqdir"] + "/{fastqid}_2.fastq"
            output:
                R1 = config["fastqdir"] + "/{fastqid}_R1.fastq"
                R2 = config["fastqdir"] + "/{fastqid}_R2.fastq"
                R3 = config["fastqdir"] + "/{fastqid}_R3.fastq"
            shell:
                "mv {input.fastq1} {output.R1}"
                "awk '{}' {input.fastq1} > {output.R2}"
                "mv {input.fastq2} {output.R3}"
    rule cellranger:
        input:
            fastqs = config["fastqdir"],
            genome = config["genome"]["cellranger"]
        output:
            stat = "Result/cellranger/" + outprefix + "/outs/singlecell.csv",
            bam = "Result/cellranger/" + outprefix + "/outs/possorted_bam.bam"
        params:
            cores = config["cores"],
            fastqprefix = config["fastqprefix"],
            outpre = outprefix,
            sourceoutdir = outprefix + "/",
            destoutdir = "Result/cellranger/"
        log:
            "Result/Log/" + outprefix + "_cellranger.log"
        shell:
            "cellranger-atac count --id={params.outpre} --fastqs={input.fastqs} "
            "--reference={input.genome} --sample={params.fastqprefix} --localcores={params.cores} "
            ">> {log};"
            "cp -fr {params.sourceoutdir} {params.destoutdir};"
            "rm -r {params.sourceoutdir};"
   
    rule short_fragment:
        input:
            bam = "Result/cellranger/" + outprefix + "/outs/possorted_bam.bam"
        output:
            fragbed = "Result/QC/" + outprefix + "_frag.bed",
            shortsam = "Result/Analysis/" + outprefix + "_50bp.sam"            
        shell:
            "mkdir Result/QC"
            "mkdir Result/Analysis"
            "samtools view {input.bam} | head -10000000 | awk '{if($9>0) print $9}' | cut -f 9 > {output.fragbed}"
            "samtools view {input.bam} | awk '{if (abs($9<=50)) print}' > {output.shortsam}"

    rule scatac_qcplot:
        input:
            stat = "Result/cellranger/" + outprefix + "/outs/singlecell.csv"
            fragbed = "Result/QC/" + outprefix + "_frag.bed",
        output:
            qcfrag = "Result/QC/" + outprefix + "_frag.pdf",
            qcmap = "Result/QC/" + outprefix + "_map.pdf",
            qcfrip = "Result/QC/" + outprefix + "_frip.pdf",
            validbarcode = "Result/QC/" + outprefix + "_barcodes.txt",
        params:
            platform = config["platform"],
            outdir = "Result/QC",
            outpre = outprefix
        shell:
            "Rscript ../R/scATACseq_qc.R {input.stat} {input.fragbed} {params.platform} {params.outpre} {params.outdir}"

    rule all_peakcall:
        input:
            bam = "Result/cellranger/" + outprefix + "/outs/possorted_bam.bam"
        output:
            bed = "Result/Analysis/" + outprefix + "_all_peaks.narrowPeak"
        params:
            name = "Result/Analysis/" + outprefix + "_all"
        log:
            "Result/Log/" + outprefix + "_macs2_allpeak.log"
        shell:
            "macs2 callpeak -g hs -n {params.name} -B -q 0.05 --nomodel --extsize=50 --SPMR -t {input.bam}"
    
    rule short_peakcall:
        input:
            sam = "Result/Analysis/" + outprefix + "_50bp.sam"            
        output:
            bed = "Result/Analysis/" + outprefix + "_50bp_peaks.narrowPeak"
        params:
            name = "Result/Analysis/" + outprefix + "_50bp"
        log:
            "Result/Log/" + outprefix + "_macs2_shortpeak.log"
        shell:
            "macs2 callpeak -g hs -n {params.name} -B -q 0.05 --nomodel --extsize=50 --SPMR -t {input.sam}"
    
    if config["custompeaks"]
        rule merge_peak:
            input:
                allpeak = "Result/Analysis/" + outprefix + "_all_peaks.narrowPeak"
                shortpeak = "Result/Analysis/" + outrefix + "_50bp_peaks.narrowPeak"
                custompeak = config["custompeaksloc"]
            output:
                custompeaksort = "Result/Analysis/" + outprefix + "_custom_peaks.bed"
                finalpeak = "Result/Analysis/" + outprefix + "_final_peaks.bed"
            shell:
                "sort -k1,1 -k2,2n {input.custompeak} > {output.custompeaksort}"
                "mergeBed -i {input.allpeak} {input.shortpeak} {output.custompeaksort} | grep -v '_' | grep -v 'chrEBV' > {output.mergepeak} "
    else:
        rule merge_peak:
            input:
                allpeak = "Result/Analysis/" + outprefix + "_all_peaks.narrowPeak"
                shortpeak = "Result/Analysis/" + outrefix + "_50bp_peaks.narrowPeak"
           output:
                finalpeak = "Result/Analysis/" + outprefix + "_final_peaks.bed"
            shell:
                "mergeBed -i {input.allpeak} {input.shortpeak} | grep -v '_' | grep -v 'chrEBV' > {output.mergepeak} "
 
    rule count_peak:
        input:
            finalpeak = "Result/Analysis/" + outprefix + "_final_peaks.bed"
            validbarcode = "Result/QC/" + outprefix + "_barcodes.txt",
            frag = "Result/cellranger/" + outprefix + "/outs/fragments.tsv.gz"
        output:
            count = "Result/Analysis/" + outprefix + "_binary.txt"
        params:
            cores = config["cores"]
        shell:
            "python ../src/scATAC_cellranger_count.py {input.finalpeak} {input.validbarcode} {input.frag} {output.count} {params.cores}"

    rule scatac_clustering:
        input:
            count = "Result/Peak/" + outprefix + "_binary.txt"
        output:
            directory("Result/Analysis")
        params:
            outpre = outprefix,
            species = config["species"],
        shell:
            "Rscript ../R/scATACseq_pipe.R {input.count} {params.species} {params.outpre} {output}"

    rule scatac_genescore:
        input:
            count = "Result/Analysis/" + outprefix + "_binary.txt"
        output:
            genescore = "Result/Analysis/" + outprefix + "_genescore.txt"
        params:
            genedistance = config["genedistance"]
            genebed = "../src/annotations/" + config["species"] +"_ensembl.bed"
            cores = config["cores"]
        shell:
            python ../src/scATAC_genescore.py {input.count} {output.genescore} {params.genedistance} {params.genebed} {params.cores}

    rule scatac_tfscore:
        input:
            count = "Result/Analysis/" + outprefix + "_binary.txt"
        output:
            tfscore = "Result/Analysis/" + outprefix + "_tfscore.txt"
        params:
            gcbed = "../src/annotations/" + config["species"] + "_window_1kb.bed",
            tfindex = "../src/annotations/" + config["species"] + "_tf_peak_loct_1kb.h5",
            tfpercent = config["tfpercent"]
            cores = config["cores"]
        shell:
            "python ../src/scATAC_TFscore.py {input.count} {output.tfcore} {params.gcbed} {params.tfindex} {params.tfpercent} {params.cores}"

