"""
A single cell RNA-seq analysis pipeline.
Author: Ming (Tommy) Tang  04/16/2020
Author: Shariq Madha
"""

from MAESTRO.scRNA_utility import SCRIPT_PATH, RSCRIPT_PATH

configfile: "config.yaml"

#include: "rules/common.smk"
# load the samples.json file
FILES = json.load(open(config['SAMPLES_JSON']))
ALL_SAMPLES = sorted(FILES.keys())

REPORTS = expand("Result/{sample}_scRNA_report.html", sample = ALL_SAMPLES)

if len(ALL_SAMPLES)>1:
    REPORTS += ["Result/%s_scRNA_report.html" % config["mergedname"]]

TARGETS = REPORTS

rule all:
    input: TARGETS

include: "rules/sc_rna_map.smk"
if config["rseqc"]:
    include: "rules/sc_rna_rseqc.smk"
if len(ALL_SAMPLES) > 1:
    include: "rules/sc_rna_merge.smk"
include: "rules/sc_rna_qc.smk"
include: "rules/sc_rna_analysis.smk"
include: "rules/sc_rna_report.smk"
