"""
Integration analysis of scATAC and scRNA
"""

configfile: "config.yaml"


import yaml
import sys
import os

from MAESTRO.scATAC_utility import SCRIPT_PATH, RSCRIPT_PATH

rule all:
    input:
        summaryreport = "Result/%s_integrate_report.html" %(config["outprefix"])

rule integrate_merge:
    input:
        atacobj = config["atacobject"],
        rnaobj = config["rnaobject"]
    output:
        mergeobject = "Result/Analysis/%s_integrate_Object.rds" %(config["outprefix"]),
        sourceplot = "Result/Analysis/%s_source.png" %(config["outprefix"]),
        rnaplot = "Result/Analysis/%s_RNAonly.png" %(config["outprefix"]),
        atacplot = "Result/Analysis/%s_ATAConly.png" %(config["outprefix"]),
        annoplot = "Result/Analysis/%s_annotated.png" %(config["outprefix"]),
    params:
        outpre = config["outprefix"],
        outdir = "Result/Analysis",
    shell:
        "Rscript " + RSCRIPT_PATH + "/integrate.R --atacobj {input.atacobj} --rnaobj {input.rnaobj} --prefix {params.outpre} --outdir {params.outdir}"

rule integrate_report:
    input:
        mergeobject = "Result/Analysis/%s_integrate_Object.rds" %(config["outprefix"]),
        sourceplot = "Result/Analysis/%s_source.png" %(config["outprefix"]),
        rnaplot = "Result/Analysis/%s_RNAonly.png" %(config["outprefix"]),
        atacplot = "Result/Analysis/%s_ATAConly.png" %(config["outprefix"]),
        annoplot = "Result/Analysis/%s_annotated.png" %(config["outprefix"]),
    output:
        summaryreport = "Result/%s_integrate_report.html" %(config["outprefix"])
    params:
        outpre = config["outprefix"],
        rnaobj = config["rnaobject"],
        atacobj = config["atacobject"],
        outdir = "Result"
    shell:
        "python " + SCRIPT_PATH + "/integrate_HTMLReport.py --outprefix {params.outpre} --rna-object {params.rnaobj} "
        "--atac-object {params.atacobj} --directory {params.outdir}"
