library(MAESTRO)
library(Seurat)
library(Matrix)
library(future)
library(future.apply)
library(pbapply)

argue = commandArgs(T)
setwd(argue[6])
# countmatrix = read.table(argue[1], sep = '\t', header = TRUE, row.names = 1, check.names = FALSE)
# RPmatrix = read.table(argue[2], sep = '\t', header = TRUE, row.names = 1, check.names = FALSE)
countmatrix = Read10X_h5(argue[1])
RPmatrix = Read10X_h5(argue[2])

plan("multiprocess", workers = as.integer(argue[7]))
options(future.globals.maxSize = 10*1024^3)
result = ATACRunSeurat(inputMat = countmatrix, project = argue[5], method = "LSI")
result$ATAC = ATACAnnotateCelltype(result$ATAC, RPmatrix, signatures = human.immune.CIBERSORT)
saveRDS(result$ATAC, paste0(argue[5], "_scATAC_Object.rds"))
result.tfs = ATACAnnotateTranscriptionFactor(ATAC = result$ATAC, peaks = result$peaks, project = argue[5], giggle.path = argue[4], organism = argue[3])
