#' Automatic cell-type annotation for scATAC-seq clusters using Cistrome Chromatin Accessibilities
#'
#' Automatic cell-type annotation for scATAC-seq clusters based on ATAC-seq peaks or DNase-seq peaks from CistromeDB. To run this function, you must first install the giggle package (see from https://github.com/ryanlayer/giggle). 
#'
#' @docType methods
#' @name ATACAnnotateChromatinAccessibility
#' @rdname ATACAnnotateChromatinAccessibility
#' 
#' @param ATAC Seurat object of ATAC RPscore clustering  generated by \code{\link{ATACAnnotateCelltype}} function.
#' @param peaks Data frame of differential peaks, generated by \code{\link{ATACRunSeurat}}, \code{\link{FindMarkersMAESTRO}} or \code{\link{FindAllMarkersMAESTRO}} function.
#' @param project Output project name for the giggle analysis result. Default is the project name of the ATAC Seurat object
#' @param giggle.path Path of the giggle annotation files. The giggle annoation for CistromeDB is available at https://github.com/liulab-dfci/MAESTRO.
#' Download and unzip the annotation, supply the path of the annotations to \code{giggle.anno.path}.
#' @param organism Organism for the dataset. Only support "GRCh38" and "GRCm38". Default is "GRCh38".
#' @param top.ca Generate barplot for the top enriched chromatin accessibility data. Default is 10, for each cluster, only the top 10 enriched chromatin accessibility data are used to generate the barplot.
#' @param min.peaks Minimum number of peaks requires to run giggle, default is 10.
#'
#' @author Dongqing Sun, Changxin Wan, Chenfei Wang
#'
#' @return A list of top enriched transcription factors and their target genes for each cluster. 
#'
#'
#' @examples
#' data(pbmc.ATAC)
#' data(pbmc.RP)
#' data(human.immune.CIBERSORT)
#' pbmc.ATAC.res <- ATACRunSeurat(inputMat = pbmc.ATAC, project = "PBMC.scATAC.Seurat", method = "LSI")
#' pbmc.ATAC.res$ATAC <- ATACAttachGenescore(pbmc.ATAC.res$ATAC, pbmc.RP)
#' pbmc.ATAC.res$ATAC <- ATACAnnotateChromatinAccessibility(ATAC = pbmc.ATAC.res$ATAC, peaks = pbmc.ATAC.res$peaks, project = "PBMC.scATAC.CA", giggle.path = "/home/annotations/giggle")
#' pbmc.ATAC.res$ATAC@meta.data
#'
#' @importFrom Seurat GetAssayData Idents
#' @import ggplot2
#' @export

ATACAnnotateChromatinAccessibility <- function(ATAC, peaks, project = ATAC@project.name, giggle.path, organism = "GRCh38", top.ca = 10, min.peaks = 10)
{
  if(nrow(peaks)<=50){
    message("Not enough differential peaks input and no enriched chromatin accessibility dataset identified.")
    ATAC@meta.data$assign.ident = "unknown"
    return(ATAC)
  }else{
    targetList <- list()
    tfList <- list()
    antFile <- read.csv(paste0(giggle.path,"/CistromeDB.sample.annotation.txt"), sep="\t", row.names=1, stringsAsFactors = FALSE)  
    outputDir <- paste0(project, ".GIGGLE")
    if (!file.exists(outputDir)){
      dir.create(path=outputDir)
    }
    ATAC@meta.data$biological_resource = 'None'
    ATAC@meta.data$CistromeCluster = 'None'
    ATAC@meta.data$CistromeClusterInfo = 'None'
    for (icluster in unique(peaks$cluster)) {
      message(paste("Identify enriched CAs for cluster ", icluster, "..."))
      ipeaks <- peaks[peaks$cluster == icluster, "peak"]
      if(length(ipeaks) > min.peaks){
      if(!file.exists(paste0(outputDir, "/", icluster, ".peaks.bed.giggle.res.cas.txt"))){
      ipeaks <- strsplit(ipeaks, "\\W")
      ipeaks <- data.frame(matrix(unlist(ipeaks), nrow=length(ipeaks), byrow=T))
      outputBed <- paste0(outputDir, "/", icluster, ".peaks.bed")
      write.table(ipeaks, outputBed, sep="\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
      targetDf = RunGiggle(peakbed = outputBed, giggle.path = giggle.path, organism = organism, antFile = antFile, type = 'ca')}
      else{
      targetDf = read.delim(paste0(outputDir, "/", icluster, ".peaks.bed.giggle.res.cas.txt"), stringsAsFactors = FALSE)
      }
      if(nrow(targetDf) >= top.ca){
      # png(paste0(outputDir, "/", icluster, ".peaks.bed.giggle.res.cas.png"), width=7,height=4, res=300)
      # par(mar=c(5,16,3,3))
      # barplot(rev(targetDf[1:top.ca,'giggle_score']),col="grey",main=paste0("Cluster ",icluster), border=NA, horiz=T,
      #         names=rev(apply(targetDf[1:top.ca,], 1, function(x) return(paste0(x[c(2,6)], collapse="_")))), xlab = "GIGGLE Score",las=2)
      # dev.off()

      targetDf <- targetDf[order(targetDf$giggle_score, decreasing = TRUE),]
      targetDf_top = targetDf[1:top.ca,]
      targetDf_top = targetDf_top[order(targetDf_top$giggle_score),]
      targetDf_top$sample_source = paste(targetDf_top$GSM_id, targetDf_top$biological_resource, sep = "_")
      targetDf_top$sample_source = factor(targetDf_top$sample_source, levels = targetDf_top$sample_source)

      RCB_blue = "#2166AC"
      theme_set(cowplot::theme_cowplot())
      png(paste0(outputDir, "/", icluster, ".peaks.bed.giggle.res.cas.png"), width=7,height=4, res = 300, units = "in")
      p = ggplot(targetDf_top, aes(x = sample_source, y = giggle_score)) + 
        geom_bar(stat="identity", fill = RCB_blue) + 
        coord_flip() + xlab(NULL) + ylab("GIGGLE Score") + 
        ggtitle(paste0("Cluster ",icluster)) + 
        scale_y_continuous(expand = c(0, 0)) +
        theme(plot.title = element_text(size = 14, hjust = 0.5), 
              axis.text.y = element_text(size = 10),
              axis.title = element_text(size = 12, hjust = 0.5),
              axis.ticks.y = element_blank(),
              axis.line.y = element_blank())
      print(p)
      dev.off()

      ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'] = as.character(targetDf[1,'biological_resource'])
      ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'] = gsub("None", "", ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'])
      ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'] = gsub("^;", "", ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'])
      ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'] = gsub(";$", "", ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'biological_resource'])
      ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'CistromeCluster'] = as.character(targetDf[1,'CistromeCluster'])
      ATAC@meta.data[ATAC@meta.data$seurat_clusters==icluster,'CistromeClusterInfo'] = as.character(targetDf[1,'CistromeClusterInfo'])
      }}
      else{
      message(paste("Skip identifying enriched CAs for cluster ", icluster, " because peak number is less than", min.peaks,"..."))
      }
    }
    ATAC@meta.data$assign.biological_resource = ATAC@meta.data$biological_resource
    ATAC@meta.data$assign.ident = ATAC@meta.data$assign.biological_resource
    return(ATAC)
  }
}

RunGiggle <- function(peakbed, giggle.path, organism, antFile, type = 'tf'){
  outputBed = peakbed
  cmd <- paste0("sort --buffer-size 2G -k1,1 -k2,2n -k3,3n ", outputBed, " | bgzip -c > ", outputBed, ".gz")
  system(cmd)
  cmd <- paste0("giggle search -i ", giggle.path, "/giggle.", organism, " -q ", outputBed, ".gz -s > ", outputBed, ".result.xls")
  system(cmd)
  resultDf <- read.table(paste0(outputBed, ".result.xls"), sep="\t", row.names=NULL, comment.char="", stringsAsFactors =  FALSE)
  resultDf <- resultDf[,-9]
  colnames(resultDf) <- c("file", "file_size", "overlaps", "odds_ratio", "fishers_two_tail", "fishers_left_tail", "fishers_right_tail", "combo_score")
  resultDf <- resultDf[resultDf$overlaps>0,]
  if(organism == "GRCh38"){
    rownames(resultDf) <- sapply(strsplit(resultDf$file, "human/"), function(x) return(gsub("_5foldPeak.bed.gz", "", x[2])))
  }
  if(organism == "GRCm38"){
    rownames(resultDf) <- sapply(strsplit(resultDf$file, "mouse/"), function(x) return(gsub("_5foldPeak.bed.gz", "", x[2])))
  }
  resultDf <- resultDf[,c("file_size", "overlaps", "combo_score")]
  targetDf <- merge(resultDf, antFile, by.x=0, by.y=0)
  colnames(targetDf) <- c("sample_id", "sample_peak_number", "overlap_peak_number", "giggle_score", "GSM_id", "species", "factor", "factor_type", "cell_line", "cell_type", "tissue", "disease")                          
  targetDf$biological_resource <- apply(targetDf, 1, function(x) return(paste0(x[9:11], collapse=";")))
  targetDf <- targetDf[, c("sample_id", "GSM_id", "species", "factor", "factor_type", "biological_resource", "giggle_score", "sample_peak_number", "overlap_peak_number")]
  targetDf_tf <- targetDf[targetDf$factor_type=='tf',]
  targetDf_tf <- targetDf_tf[order(-targetDf_tf$giggle_score), ]
  targetDf_tf <- targetDf_tf[!duplicated(targetDf_tf$factor), ]
  write.table(targetDf_tf, paste0(outputBed, ".giggle.res.tfs.txt"), sep="\t", quote=FALSE, row.names=FALSE)
  
  targetDf_ca <- targetDf[targetDf$factor_type=='ca',]
  ATAC_cluster <- read.csv(paste0(giggle.path,"/ATAC_with_log_peaks_RP_hierarchical_sample_80_clusters.csv"), sep=",", row.names=1, stringsAsFactors = FALSE)  
  DNase_cluster <- read.csv(paste0(giggle.path,"/DNAse_with_log_peaks_RP_hierarchical_sample_80_clusters.csv"), sep=",", row.names=1, stringsAsFactors = FALSE)  
  ATAC_cluster$combined <- apply(ATAC_cluster, 1, function(x) return(paste0(x[2:3], collapse="_")))
  ATAC_cluster$clusterinfo <-  apply(ATAC_cluster, 1, function(x) return(paste0(x[2:3], collapse="_")))
  for(i in 1:nrow(ATAC_cluster)){ATAC_cluster[i,'CistromeClusterInfo'] <- paste0(unique(ATAC_cluster[ATAC_cluster$CistromeCluster==ATAC_cluster[i,'CistromeCluster'],'combined']),collapse=";")}
  ATAC_cluster <- ATAC_cluster[,c('CistromeCluster','CistromeClusterInfo')]
  DNase_cluster$combined <- apply(DNase_cluster, 1, function(x) return(paste0(x[2:3], collapse="_")))
  DNase_cluster$clusterinfo <-  apply(DNase_cluster, 1, function(x) return(paste0(x[2:3], collapse="_")))
  for(i in 1:nrow(DNase_cluster)){DNase_cluster[i,'CistromeClusterInfo'] <- paste0(unique(DNase_cluster[DNase_cluster$CistromeCluster==DNase_cluster[i,'CistromeCluster'],'combined']),collapse=";")}
  DNase_cluster <- DNase_cluster[,c('CistromeCluster','CistromeClusterInfo')]
  ca_cluster <- rbind(ATAC_cluster, DNase_cluster)
  targetDf_ca <- merge(targetDf_ca, ca_cluster, by.x="sample_id", by.y=0)
  targetDf_ca <- targetDf_ca[order(-targetDf_ca$giggle_score), ]
  write.table(targetDf_ca, paste0(outputBed, ".giggle.res.cas.txt"), sep="\t", quote=FALSE, row.names=FALSE)

  cmd <- paste0("rm ", outputBed, ".gz")
  system(cmd)
  if(type == 'tf'){return(targetDf_tf)}
  if(type == 'ca'){return(targetDf_ca)}
}

multimerge <- function (mylist) {
  ## mimics a recursive merge or full outer join
 
  unames <- unique(unlist(lapply(mylist, rownames)))
 
  n <- length(unames)
 
  out <- lapply(mylist, function(df) {
 
    tmp <- matrix(nr = n, nc = ncol(df), dimnames = list(unames,colnames(df)))
    tmp[rownames(df), ] <- as.matrix(df)
    rm(df); gc()
 
    return(tmp)
  })
 
  stopifnot( all( sapply(out, function(x) identical(rownames(x), unames)) ) )
 
  bigout <- do.call(cbind, out)
  colnames(bigout) <- paste0(rep(names(mylist), sapply(mylist, ncol)), unlist(sapply(mylist, colnames)))
  return(bigout)
}