#' Read distribution plot for scATAC-seq analysis
#'
#' Summary plot of total reads, duplicate reads ratio, mappability, mitochondria and peak reads ratio for scATAC-seq analysis.
#'
#' @docType methods
#' @name ATACReadDistrPlot
#' @rdname ATACReadDistrPlot
#'
#' @param filepath Path of the fragment size file generated by \code{MAESTRO}.
#' @param name Name for the output fragment size distribution plot.
#'
#' @author Chenfei Wang, Dongqing Sun
#'
#' @export

ATACReadDistrPlot <- function(filepath, name)
{
  require(ggplot2)
  require(cowplot)
  theme_set(theme_cowplot())
  RCB_blue = "#2166AC"
  
  bam_stat_list = readLines(filepath)[c(1,4,15,14,17,16)]
  total_reads = unlist(strsplit(bam_stat_list[1], split = " "))[1]
  dup_reads = unlist(strsplit(bam_stat_list[2], split = " "))[1]
  map_list = as.integer(c(total_reads, dup_reads, bam_stat_list[3:6]))/1000000
  map_ratio_list = round(map_list*100/map_list[1],2)
  map_ratio_list = paste0(map_ratio_list, "%")
  Group = c("Total reads", "Duplicate reads", "Unique mapped reads","Mitochondria reads", "Peak reads", "Promoter reads")
  map_df = data.frame(ReadCount = map_list, Group, stringsAsFactors = FALSE)
  map_df$Group = factor(map_df$Group, levels = Group)
  
  png(paste0(name ,"_scATAC_read_distr.png"), width=4.5,height=4.8, res = 300, units = "in")
  p = ggplot(map_df, aes(x = Group, y = ReadCount)) + 
    geom_bar(stat="identity", fill = RCB_blue) + 
    xlab(NULL) + ylab("Read counts (M)")  + 
    theme(axis.title = element_text(size = 13), axis.text.y = element_text(size = 12, angle = 90, hjust = 0.5), 
          axis.text.x = element_text(angle = 45, size = 12, hjust = 1), axis.ticks.x = element_blank(),
          legend.position="none", axis.title.y = element_text(margin = margin(r = 20, unit = "pt")))+ 
    geom_text(aes(label = map_ratio_list, y = ReadCount + 30), size = 4.8)
  print(p)
  dev.off()
}