#' Estimate gene activity from peak using regulatory potential model
#'
#' Calculate gene score according to scATAC peak count.
#'
#' @docType methods
#' @name ATACCalculateGenescore
#' @rdname ATACCalculateGenescore
#' 
#' @param inputMat Input unnormalized count matrix, with peaks as rows and cells as columns. Rownames should be like "chromosome_peakstart_peakend",
#' for example "chr10_100020591_100020841". It can be a sparse matrix or a dense matrix. But we recommend to use the sparse one, because 
#' this will result in significant memory and speed savings.
#' @param project Output project name for the gene sore result.Default is "MAESTRO.scATAC".
#' @param organism Organism for the dataset. Only support "GRCh38" and "GRCm38". Default is "GRCh38".
#'
#' @author Dongqing Sun, Changxin Wan, Chenfei Wang
#'
#' @return Sparse matrix of regulatory potential generated by MAESTRO. With genes as rows and cells as columns,
#' and gene RP score as values.
#'
#'
#' @examples
#' data(pbmc.ATAC)
#' pbmc.ATAC.RP.res <- ATACCalculateGenescore(inputMat = pbmc.ATAC)
#'
#' @export 
#' 

ATACCalculateGenescore <- function(inputMat, project = "MAESTRO.scATAC", organism = "GRCh38"){
  library(reticulate)
  library(Matrix)
  source_python(paste(system.file(package="MAESTRO"), "ATACCalculateGenescore.py", sep="/"))
  
  if(organism == "GRCh38"){
    data(GRCh38.ensembl.genescore)
    ensembl.genescore = GRCh38.ensembl.genescore
  }else{
    data(GRCm38.ensembl.genescore)
    ensembl.genescore = GRCm38.ensembl.genescore
  }
  
  genes_list = ensembl.genescore[,4]
  ensembl.genescore = ensembl.genescore[,-4]
  
  peaks_list = rownames(inputMat)
  peaks_list = gsub(pattern = "\\W", replacement = "_", x = peaks_list)
  if(class(inputMat) != "dgCMatrix"){
    inputMat = as(as.matrix(inputMat), "dgCMatrix")
  }
  
  rp_result = calculate_RP_score(cell_peaks = inputMat, peaks_list = peaks_list, genes_info = ensembl.genescore, 
                                 genes_list = genes_list, decay = 10000)
  rp_matrix = rp_result[[1]]
  rownames(rp_matrix) = rp_result[[2]]
  colnames(rp_matrix) = colnames(inputMat)
  
  return(rp_matrix)
}

