#' Add gene score (gene activity) matrix to an ATAC Seurat object
#'
#' Add gene score (gene activity) matrix to an ATAC Seurat object and normalize it.
#'
#' @docType methods
#' @name ATACAttachGenescore
#' @rdname ATACAttachGenescore
#'
#' @param ATAC Seurat object of clustered scATAC-seq dataset, generated by \code{\link{ATACRunSeurat}} function.
#' @param RPmatrix Regulatory potential matrix generated by \code{\link{ATACCalculateGenescore}}. 
#' With genes as rows and cells as columns, and gene RP score as values.
#'
#' @author Chenfei Wang, Dongqing Sun
#'
#' @return An ATAC Seurat object with ACTIVITY attached.
#'
#'
#' @examples
#' data(pbmc.ATAC)
#' data(pbmc.RP)
#' pbmc.ATAC.res <- ATACRunSeurat(inputMat = pbmc.ATAC, project = "PBMC.scATAC.Seurat", method = "LSI")
#' pbmc.ATAC.res$ATAC <- ATACAttachGenescore(pbmc.ATAC.res$ATAC, pbmc.RP)
#' str(pbmc.ATAC.res$ATAC)
#'
#' @importFrom Seurat CreateAssayObject DefaultAssay FindVariableFeatures NormalizeData ScaleData
#' @export

ATACAttachGenescore <- function(ATAC, RPmatrix)
{
  RPmatrix <- RPmatrix[,colnames(ATAC)]
  ATAC[["ACTIVITY"]] <- CreateAssayObject(counts = RPmatrix)
  DefaultAssay(ATAC) <- "ACTIVITY"
  ATAC <- FindVariableFeatures(ATAC)
  ATAC <- NormalizeData(ATAC)
  ATAC <- ScaleData(ATAC)
  
  return(ATAC)
}
