#' Annotate celltype based on marker genes for one cluster
#'
#' Annotate the celltype for one cluster based on the marker genes of that cluster and celltype signatures.
#'
#' @docType methods
#' @name RNAAnnotateCelltypeCluster
#' @rdname RNAAnnotateCelltypeCluster
#'
#' @param genes Data frame of differential expressed genes, generated by \code{\link{RNARunSeurat}} function.
#' @param signatures The \code{signatures} can be character or data frame. If \code{signatures} is character, 
#' it should be "human.immune.CIBERSORT", "mouce.brain.ALLEN", "mouse.all.facs.TabulaMuris" or "mouse.all.droplet.TabulaMuris".
#' If \code{signatures} is a data frame, is should be a data frame of celltype signatures, with first column is celltype, and second column is
#' gene symbol. Check the immune signatures from CIBERSORT (Newman et al., Nature Method, 2015) in example for details. Default is "human.immune.CIBERSORT".
#' @param cluster Cluster ID. Default is 0. Check the celltype identify of cluster 0.
#'
#' @author Chenfei Wang
#'
#' @return An list of ranked celltype score based on given signatures.
#'
#'
#' @examples
#' data(pbmc.RNA)
#' data(human.immune.CIBERSORT)
#' pbmc.RNA.res <- RNARunSeurat(inputMat = pbmc.RNA, project = "PBMC.scRNA.Seurat", min.c = 10, min.g = 100, dims.use = 1:15)
#' celtype.score <- RNAAnnotateCelltypeCluster(pbmc.RNA.res$genes, human.immune.CIBERSORT, cluster = 0)
#' celtype.score
#'
#' @export

RNAAnnotateCelltypeCluster <- function(genes, signatures = "human.immune.CIBERSORT", cluster = 0){
    if(class(signatures) == "character"){
        data(list = signatures)
        signatures = get(signatures)
    }
    celltypes <- as.character(unique(signatures[,1]))
    signature_list <- sapply(1:length(celltypes),function(x){
                      return(toupper(as.character(signatures[which(signatures[,1]==celltypes[x]),2])))})
    names(signature_list) <- celltypes
    idx = genes$cluster==cluster
    avglogFC = genes$avg_logFC[idx]
    names(avglogFC) = toupper(genes$gene[idx])
    score_cluster = sapply(signature_list, function(x){
                    score = sum(avglogFC[x], na.rm = TRUE) / log2(length(x))
                    return(score)
    })
    return(sort(score_cluster, decreasing=T)) 
}
