#' Remove batch effect in scRNA-seq dataset
#'
#' Remove batch effect from scRNA-seq dataset, batch information should be provided, remove the batch and perform clustering again.
#'
#' @docType methods
#' @name RNABatchCorrect
#' @rdname RNABatchCorrect
#'
#' @param RNA Seurat object of clustered scRNA-seq dataset, generated by \code{\link{RNARunSeurat}} function.
#' @param batch List of batch information, should be the same with the column names (cell name) with RNA object.
#' @param project Output project name. Default is "MAESTRO.coembedded".
#' @param nfeatures Number of the features used in the CCA analysis, default is 2000, use top 2000 HVG features from each batch.
#' @param dims.use Number of dimensions used for UMAP analysis. Default is 1:15, use the first 15 PCs.
#' @param cluster.res Value of the clustering resolution parameter. Default is 0.6.
#'
#' @author Chenfei Wang
#'
#' @return A list contains a RNA Seurat object with batch removed and a data frame for the cluster specific genes. 
#'
#'
#' @examples
#' 
#' @importFrom Seurat DefaultAssay DimPlot FindClusters FindIntegrationAnchors FindNeighbors FindVariableFeatures IntegrateData NormalizeData RunPCA RunUMAP ScaleData SplitObject
#' @importFrom ggplot2 ggplot ggsave
#' @importFrom Gmisc fastDoCall
#' @export

RNABatchCorrect <- function(RNA, batch, nfeatures = 2000, dims.use = 1:15, cluster.res = 0.6, only.pos = FALSE, genes.test.use = "presto", 
                            genes.cutoff = 1E-5, genes.pct = 0.1, genes.logfc = 0.25,
                            runpca.agrs = list(), findneighbors.args = list(), 
                            findclusters.args = list(), ...){
    RNA@meta.data$batch <- batch
    data.list <- SplitObject(RNA, split.by = "batch")
    for(i in 1:length(data.list)){
    data.list[[i]] <- NormalizeData(data.list[[i]], verbose = FALSE)
    data.list[[i]] <- FindVariableFeatures(data.list[[i]], selection.method = "vst", nfeatures = nfeatures, verbose = FALSE)
    }
   
    anchors <- FindIntegrationAnchors(object.list = data.list, dims = dims.use, anchor.features = nfeatures)
    RNA.integrated <- IntegrateData(anchorset = anchors, dims = dims.use)
    RNA.integrated@project.name <- paste0(RNA@project.name,'_CCA')
    DefaultAssay(RNA.integrated) <- "integrated"
    
    RNA.integrated <- ScaleData(RNA.integrated, verbose = FALSE)
    RNA.integrated <- fastDoCall("RunPCA", c(object = RNA.integrated, runpca.agrs))
    p = ElbowPlot(object = RNA.integrated, ndims = RNA.integrated@commands$RunPCA.integrated@params$npcs)
    ggsave(file.path(paste0(RNA.integrated@project.name, "_PCElbowPlot.png")), p,  width=10, height=4)
    
    RNA.integrated <- RunUMAP(object = RNA.integrated, reduction = "pca", dims = dims.use, ...)
    RNA.integrated <- fastDoCall("FindNeighbors", c(object = RNA.integrated, reduction = "pca", dims = dims.use, findneighbors.args))
    RNA.integrated <- fastDoCall("FindClusters", c(object = RNA.integrated, resolution = cluster.res, findclusters.args))

    p = DimPlot(object = RNA.integrated, label = TRUE, pt.size = 0.2)
    ggsave(file.path(paste0(RNA.integrated@project.name, "_cluster.png")), p, width=5, height=4)
    p = DimPlot(object = RNA.integrated, group = 'batch', label = TRUE, pt.size = 0.2)
    ggsave(file.path(paste0(RNA.integrated@project.name, "_batch.png")), p, width=5.5, height=4)

    cluster.genes <- FindAllMarkersMAESTRO(object = RNA.integrated, only.pos = only.pos, min.pct = genes.pct, test.use = genes.test.use, logfc.threshold = genes.logfc)
    cluster.genes <- cluster.genes[cluster.genes$p_val_adj < genes.cutoff, ]
    write.table(cluster.genes, paste0(RNA.integrated@project.name, "_DiffGenes.tsv"), quote = F, sep = "\t")

    return(list(RNA=RNA.integrated, genes=cluster.genes))
}