#' Perform lineage tracing analysis in scRNA-seq dataset
#'
#' Perform lineage tracing analysis in scRNA-seq dataset using Diffusion map.
#'
#' @docType methods
#' @name RNADiffusionMap
#' @rdname RNADiffusionMap
#'
#' @param RNA Seurat object of clustered scRNA-seq dataset, generated by \code{\link{RNARunSeurat}} function.
#' @param project Output project name. Default is the RNA Seurat object name.
#' @param start.genes Genes used for the start.
#' @param end.genes Genes used for the end.
#' @param clusters Clusters for perform diffusion map analysis, default use all the clusters.
#'
#' @author Chenfei Wang
#'
#' @return A diffusion map object with pseudo time information. 
#'
#' @examples
#' 
#' @importFrom ggplot2 aes ggplot ggtitle theme_classic xlab ylab
#' @export

RNADiffusionMap <- function(RNA, project = RNA@project.name, start.genes, end.genes , clusters = unique(RNA@meta.data$seurat_clusters))
{
  library(destiny)
  library(ggthemes)
  library(ggbeewarm)
  cells <- RNA@meta.data[which(RNA@meta.data$seurat_clusters %in% clusters),]
  genes <- c(start.genes, end.genes)
  dm.data <- RNA@data[intersect(rownames(RNA@data),genes),rownames(cells)]
  dm <- DiffusionMap(t(as.matrix(dm.data)))
  dm.res <- data.frame(DC1 = -eigenvectors(dm)[,1], DC2 = eigenvectors(dm)[,2], Timepoint = cells$assign.ident) 
  pdf(paste0(project,"_pseudotime.pdf"),width=6.5,height=4.5)
  p <- ggplot(dm.res, aes(x = DC1,y = Timepoint, colour = Timepoint)) +
         geom_quasirandom(groupOnX = FALSE) +
         scale_color_tableau() + theme_classic() +
         xlab("Diffusion map pseudotime (first diffusion map component)") + ylab("Timepoint") +
         ggtitle(paste0(project," pseudotime")) 
  p 
  dev.off()
  return(dm)
}