#' Cell filtering plot for scRNA-seq analysis
#'
#' Filtering the cells and non-cells based on number of UMIs and covered genes in each cell.
#'
#' @docType methods
#' @name RNAFilteringPlot
#' @rdname RNAFilteringPlot
#'
#' @param filepath Path of the scRNA-seq mapping sumary file generated by \code{MAESTRO}.
#' @param UMI.cutoff UMI cutoff. Cells with less than \code{UMI.cutoff} UMIs will be classified as low-quality cells.
#' Default is 1000.
#' @param gene.number.cutoff Gene number cutoff. Cells covered less than \code{gene.number.cutoff} will be 
#' classified as non-cells. Default is 500.
#' @param name Name for the output cell filtering plot and valid cells file.
#'
#' @author Dongqing Sun, Chenfei Wang
#'
#' @export

RNAFilteringPlot <- function(filepath, UMI.cutoff = 1000, gene.number.cutoff = 500, name){
  RCB_blue = "#2166AC"
  RCB_red = "#B2182B"

  UMI_gene = read.table(filepath, header = TRUE, row.names = 1)
  png(paste0(name,"_scRNA_cell_filtering.png"),width=4.8,height=4.8, res = 300, units = "in")
  par(mai = c(0.85, 0.85, 0.25, 0.25))
  plot(log10(UMI_gene[which(UMI_gene[,1] < UMI.cutoff | UMI_gene[,2] < gene.number.cutoff),1]+1),UMI_gene[which(UMI_gene[,1] < UMI.cutoff | UMI_gene[,2] < gene.number.cutoff),2],
       xlim=c(0,log10(max(UMI_gene[,1])+1)+0.25), ylim=c(0,max(UMI_gene[,2])+150), pch='.',col=RCB_red,ylab='Number of genes covered',xlab='Number of UMIs (log10)')
  points(log10(UMI_gene[which(UMI_gene[,1] >= UMI.cutoff & UMI_gene[,2] >= gene.number.cutoff),1]+1),UMI_gene[which(UMI_gene[,1] >= UMI.cutoff & UMI_gene[,2] >= gene.number.cutoff),2],
         pch='.',col=RCB_blue)
  legend("topleft",c("High-quality cells","Low-quality cells"),col=c(RCB_blue,RCB_red),pch=20, bty = "n")
  dev.off()
  # write.table(as.character(rownames(UMI_gene[which(UMI_gene[,1]>=UMI.cutoff&(UMI_gene[,2]>=gene.number.cutoff)),])), paste0(name,"_scRNA_validcells.txt"), sep = "\n", quote=F, row.names=F, col.names=F)
}