#' Genebody coverage plot for scRNA-seq analysis
#'
#' Generate the genebody coverage plot for scRNA-seq quality control analysis.
#'
#' @docType methods
#' @name RNAGenebodyCoveragePlot
#' @rdname RNAGenebodyCoveragePlot
#'
#' @param filepath Path of the genebody coverage file generated by \code{MAESTRO}.
#' @param name Name for the output genebody coverage plot.
#'
#' @author Dongqing Sun, Chenfei Wang
#'
#' @export

RNAGenebodyCoveragePlot <- function(filepath, name){
  RCB_blue = "#2166AC"

  gene_cov = as.data.frame(t(read.table(filepath, header = FALSE, row.names = 1, sep = "\t")))
  row.names(gene_cov) = NULL
  gene_cov$Coverage = (gene_cov[,2]-min(gene_cov[,2]))/(max(gene_cov[,2])-min(gene_cov[,2]))
  png(paste0(name, "_scRNA_genebody_cov.png"), width = 4.8,height = 4.8, res = 300, units = "in")
  par(mai = c(0.9,0.9,0.25,0.25))
  plot(gene_cov$Percentile,gene_cov$Coverage,type='l',xlab="Gene body percentile (5'->3')", ylab="Coverage",lwd=2,col=RCB_blue)
  dev.off()
}