#' GC content plot for scRNA-seq QC
#'
#' Generate the GC content plot for scRNA-seq quality control analysis.
#'
#' @docType methods
#' @name RNAGCcontentPlot
#' @rdname RNAGCcontentPlot
#'
#' @param filepath Path of the GC content file generated by \code{MAESTRO}.
#' @param name Name for the output GC content plot.
#'
#' @author Dongqing Sun, Chenfei Wang
#'
#' @export

RNAGCcontentPlot <- function(filepath, name){
  RCB_blue = "#2166AC"

  GC_content = read.table(filepath, header = TRUE, sep = "\t")
  gc=rep(GC_content[,1],times = GC_content[,2])
  png(paste0(name, "_scRNA_GCcontent.png"), width = 4.8,height = 4.8, res = 300, units = "in")
  par(mai = c(0.85,0.85,0.25,0.25))
  hist(gc,probability=T,breaks=100,xlab="GC content (%)",ylab="Density of Reads",border=RCB_blue,main="")
  dev.off()
}