#' NVC plot for scRNA-seq QC
#'
#' Generate the NVC(Nucleotide versus cycle) plot for scRNA-seq quality control analysis.
#'
#' @docType methods
#' @name RNANucleotidePlot
#' @rdname RNANucleotidePlot
#'
#' @param filepath Path of the nucleotide composition file generated by \code{MAESTRO}.
#' @param name Name for the output NVC plot.
#'
#' @author Dongqing Sun, Chenfei Wang
#'
#' @export

RNANucleotidePlot <- function(filepath, name){
  NVC = read.table(filepath, header = TRUE)
  position = NVC[,1]
  A_count = NVC[,2]
  C_count = NVC[,3]
  G_count = NVC[,4]
  T_count = NVC[,5]
  total= A_count + C_count + G_count + T_count
  ym = max(A_count/total, C_count/total, G_count/total, T_count/total) + 0.05
  yn = min(A_count/total, C_count/total, G_count/total, T_count/total)
  png(paste0(name, "_scRNA_NVC.png"), width = 4.8,height = 4.8, res = 300, units = "in")
  par(mai = c(0.85,0.85,0.25,0.25))
  plot(position, A_count/total, type="o", pch=20, cex = 0.6, ylim=c(yn,ym), col="dark green", xlab="Position of Read", ylab="Nucleotide Frequency")
  lines(position, T_count/total, type="o", pch=20, cex = 0.6, col="red4")
  lines(position, G_count/total, type="o", pch=20, cex = 0.6, col="navy")
  lines(position, C_count/total, type="o", pch=20, cex = 0.6, col="steel blue")
  legend("topright", legend=c("A","T","G","C"), col=c("dark green","red4","navy","steel blue"), bty = "n", pch=20, cex = 0.6, lwd=2, text.col=c("dark green","red4","navy","steel blue"))
  dev.off()
}