#' Read quality plot for scRNA-seq analysis
#'
#' Generate the read quality plot for scRNA-seq quality control analysis.
#'
#' @docType methods
#' @name RNAReadQualityPlot
#' @rdname RNAReadQualityPlot
#'
#' @param filepath Path of the read quality r file generated by \code{MAESTRO}.
#' @param name Name for the output read quality plot.
#'
#' @author Dongqing Sun, Chenfei Wang
#'
#' @export

RNAReadQualityPlot <- function(filepath, name){
  codelist = readLines(filepath)
  heatmap_codelist = codelist[(length(codelist)-4):(length(codelist)-1)]
  png(paste0(name, "_scRNA_read_quality.png"), width = 6,height = 6, res = 300, units = "in")
  par(mai = c(0.2,0.2,0.85,0.85))
  for(i in 1:length(heatmap_codelist)){
    eval(parse(text = heatmap_codelist[i]))
  }
  dev.off()
}