#' UMAP plot to show expression level or regulatory potential of genes
#'
#' Draw a UMAP plot to show the expression level (RNA) or regulatory potential (ATAC) of given genes in different clusters.
#'
#' @docType methods
#' @name VisualizeUmap
#' @rdname VisualizeUmap
#'
#' @param genes Genes or TFs to plot.
#' @param type Type of the dataset. If \code{type} is "RNA", the expression level of genes will be visulized. 
#' If \code{type} is "ATAC", the regulatory potential will be used.
#' @param SeuratObj A Seurat object. If \code{type} is "RNA", \code{SeuratObj} should be the Seurat object generated by \code{\link{RNARunSeurat}} function.
#' If \code{type} is "ATAC", \code{SeuratObj} should be a Seurat object created using RP matrix achievesd from \code{\link{ATACAnnotateCelltype}} function.
#' @param ncol Number of columns by which multiple plots are arranged.
#' @param width Width of the plots.
#' @param height Height of the plots.
#' @param name Output name of the plots. Default is "MultipleUmapPlot".
#'
#' @author Chenfei Wang, Dongqing Sun
#'
#' @examples
#' data(pbmc.RNA)
#' pbmc <- RNARunSeurat(inputMat = pbmc.RNA, project = "PBMC.scRNA.Seurat")
#' pbmc.tfs <- RNAAnnotateTranscriptionFactor(pbmc$RNA, pbmc$genes, project = "PBMC.scRNA.TF", method = "LISA")
#' 
#' # TFs of interest
#' tfs = sapply(pbmc.tfs[[1]], function(x){return(unlist(strsplit(x, split = " | ", fixed = TRUE))[1])})
#' VisualizeUmap(genes = tfs, type = "RNA", SeuratObj = pbmc$RNA, ncol = 5, width = 6, height = 3, name = "PBMC.scRNA.tf")
#'
#' # Genes of interest
#' VisualizeUmap(genes = c("MS4A1","FCGR3A","CD3D","GZMB"), type = "RNA", SeuratObj = pbmc$RNA, ncol = 2, width = 7, height =4.5, name = "PBMC.scRNA.genes")
#' 
#' 
#' @importFrom Seurat CombinePlots GetAssayData
#' @importFrom ggplot2 aes element_blank element_line geom_point ggplot ggsave labs scale_color_gradient theme
#' @export

VisualizeUmap <- function(genes, type, SeuratObj, ncol = NULL, width = 6, height = 4, name = "MultipleUmapPlot"){
  if(type == "ATAC"){
    genes = intersect(rownames(SeuratObj$ACTIVITY),unique(genes))
    if(length(genes) == 0){
      stop("The input genes are not detected!")
    }
    gene_expr = GetAssayData(object = SeuratObj$ACTIVITY)[genes, ]
  }
  if(type == "RNA"){
    genes = intersect(rownames(SeuratObj),unique(genes))
    if(length(genes) == 0){
      stop("The input genes are not detected!")
    }
    gene_expr = GetAssayData(object = SeuratObj)[genes, ]
  }
  if (length(genes) == 1){
    gene_expr_mat = matrix(gene_expr, nrow = 1)
    colnames(gene_expr_mat) = names(gene_expr)
    rownames(gene_expr_mat) = genes
  } else {
    gene_expr_mat = gene_expr
  }
  umap_df = SeuratObj@reductions$umap@cell.embeddings
  umapplots = lapply(genes, function(x){
    umap_expr = merge(umap_df, as.data.frame(gene_expr_mat[x, ]), by.x = 0, by.y = 0)
    row.names(umap_expr) = umap_expr[,1]
    umap_expr = umap_expr[,-1]
    colnames(umap_expr)[3] = "Gene"
    
    if(type == "RNA"){
      legendtitle = "Expression level"}
    if(type == "ATAC"){
      legendtitle = "RP score"}
    p = ggplot(umap_expr, aes(x = UMAP_1, y = UMAP_2, colour = Gene)) + 
      geom_point(aes(colour = Gene), size = 0.2) + 
      scale_color_gradient(name = legendtitle,low="lightgrey", high="darkblue") +
      labs(title = x) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(), axis.line = element_line(colour = "black"))
    return(p)
  })
  combinedplot = CombinePlots(umapplots, ncol = ncol)
  ggsave(paste0(name, "_umapplot.png"), combinedplot,  width=width, height=height)  
}



