#' UMAP plot to show expression level or regulatory potential of genes
#'
#' Draw a UMAP plot to show the expression level (RNA) or regulatory potential (ATAC) of given genes in different clusters.
#'
#' @docType methods
#' @name VisualizeUmap
#' @rdname VisualizeUmap
#'
#' @param genes Genes to plot. Either TF list generated by \code{\link{RNAAnnotateTranscriptionFactor}} function and \code{\link{ATACAnnotateTranscriptionFactor}} function 
#' or a vector of genes of interst.
#' @param cluster The top TF in which cluster. If \code{genes} is a vector of genes, \code{cluster} will not work.
#' @param type Type of the dataset. If \code{type} is "RNA", the expression level of genes will be visulized. 
#' If \code{type} is "ATAC", the regulatory potential will be used.
#' @param SeuratObj A Seurat object. If \code{type} is "RNA", \code{SeuratObj} should be the Seurat object generated by \code{\link{RNARunSeurat}} function.
#' If \code{type} is "ATAC", \code{SeuratObj} should be a Seurat object created using RP matrix achievesd from \code{\link{ATACAnnotateCelltype}} function.
#' @param ncol Number of columns by which multiple plots are arranged.
#' @param width Width of the plots.
#' @param height Height of the plots.
#' @param name Output name of the plots. Default is "MultipleUmapPlot".
#'
#' @author Chenfei Wang, Dongqing Sun
#'
#' @examples
#' data(pbmc.RNA)
#' pbmc <- RNARunSeurat(inputMat = pbmc.RNA, project = "PBMC.scRNA.Seurat")
#' pbmc.tfs <- RNAAnnotateTranscriptionFactor(pbmc$RNA, pbmc$genes, project = "PBMC.scRNA.TF", rabit.path = "/home/annotations/rabit")
#' VisualizeUmap(genes = pbmc.tfs, cluster = "0", type = "RNA", SeuratObj = pbmc, ncol = 5, width = 6, height = 3, name = "PBMC.scRNA.tf")
#'
#' # Genes of interest
#' VisualizeUmap(genes = c("MS4A1","FCGR3A","CD3D","GZMB"), type = "RNA", SeuratObj = pbmc$RNA, ncol = 2, width = 7, height =4.5, name = "PBMC.scRNA.genes")
#' 
#' @export

VisualizeUmap <- function(genes, cluster, type, SeuratObj, ncol = NULL, width = 6, height = 4, name = "MultipleUmapPlot"){
  require(ggplot2)
  if(is.list(genes)){
    genes = genes[[cluster]]
    genes = sapply(genes, function(x){
      return(unlist(strsplit(x, split = " | ", fixed = TRUE))[1])
    })
    names(genes) = NULL
  }
  genes = intersect(rownames(SeuratObj),unique(genes))
  gene_expr = GetAssayData(object = SeuratObj)[genes, ]
  umap_df = SeuratObj@reductions$umap@cell.embeddings
  umapplots = lapply(genes, function(x){
    umap_expr = merge(umap_df, as.data.frame(gene_expr[x, ]), by.x = 0, by.y = 0)
    row.names(umap_expr) = umap_expr[,1]
    umap_expr = umap_expr[,-1]
    colnames(umap_expr)[3] = "Gene"
    
    if(type == "RNA"){
      legendtitle = "Expression level"}
    if(type == "ATAC"){
      legendtitle = "RP score"}
    p = ggplot(umap_expr, aes(x = UMAP_1, y = UMAP_2, colour = Gene)) + 
      geom_point(aes(colour = Gene), size = 0.2) + 
      scale_color_gradient(name = legendtitle,low="lightgrey", high="darkblue") +
      labs(title = x) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(), axis.line = element_line(colour = "black"))
    return(p)
  })
  combinedplot = CombinePlots(umapplots, ncol = ncol)
  ggsave(paste0(name, "_umap.png"), combinedplot,  width=width, height=height)  
}



