#' Scatter plot to show the enrichment of TFs 

#' Draw a scatter plot to show the enrichment of TFs in specific clusters, based on cluster-specific TFs or cluster-specific peaks. Currently only support LISA for scRNA-seq analysis and GIGGLE for scATAC-seq analysis.
#'
#' @docType methods
#' @name VisualizeTFenrichment
#' @rdname VisualizeTFenrichment
#'
#' @param TFs TFs to plot.  If no TFs is given, by default visualize the top \code{visual.topnumber} regulators in that cluster. For "Incorparated" result, is no TFs is given,
#' using the rank from GIGGLE analysis on scATAC-seq dataset.
#' @param cluster.1 ClusterID for which the regulators need to be plotted.
#' @param cluster.2 For integrated result, cluster.1 represent the clusterID for scRNA-seq, cluster.2 represent the clusterID for scATAC-seq, default set to NULL when only
#' RNA or ATAC is analyzed.
#' @param type Type of the dataset. If \code{type} is "RNA" or "Integrated", the expression level of TFs will be visualized. 
#' If \code{type} is "ATAC", the regulatory potential will be used for visualization. Default is "RNA".
#' @param SeuratObj A Seurat object. If \code{type} is "RNA"or "Integrated", \code{SeuratObj} should be the Seurat object generated by \code{\link{RNARunSeurat}} function.
#' If \code{type} is "ATAC", \code{SeuratObj} should be a Seurat object created using RP matrix achievesd from \code{\link{ATACAnnotateCelltype}} function.
#' @param visual.topnumber If "top" is used, select top ranked regulators for labeling, default is top 10.
#' @param visual.totalnumber Number of total visualized regulators, default is top 100.
#' @param LISA.table Path of the score summary tale for LISA, default is \code{project.name_}TF_lisa.txt.
#' @param GIGGLE.table Path of the score summary tale for GIGGLE, default is \code{project.name_}TF_giggle.txt.
#' @param width Width of the plots.
#' @param height Height of the plots.
#' @param name Output name of the plots. Default is "TFEnrichmentPlot".
#'
#' @author Chenfei Wang, Dongqing Sun
#'
#' @return A ggplot object which can be visulaized by \code{link{print}}.
#'
#' @examples
#' data(pbmc.RNA)
#' pbmc <- RNARunSeurat(inputMat = pbmc.RNA, project = "PBMC.scRNA.Seurat")
#' pbmc.tfs <- RNAAnnotateTranscriptionFactor(pbmc$RNA, pbmc$TFs, project = "PBMC.scRNA.TF", method = "LISA")
#' 
#' # TFs from MAESTRO result
#' tfs = sapply(pbmc.tfs[[1]], function(x){return(unlist(strsplit(x, split = " | ", fixed = TRUE))[1])})
#' VisualizeTFenrichment(TFs = tfs, cluster.1 = 0, type = "RNA", SeuratObj = pbmc$RNA, visual.topnumber = 10, visual.totalnumber = 100, width = 6, height = 3, name = "PBMC.scRNA.tf")
#'
#' # TFs of interest
#' VisualizeTFenrichment(TFs = c("CEBPA","CEBPB","CEBPD"), cluster.1 = 0, type = "RNA", SeuratObj = pbmc$RNA, visual.totalnumber = 100, width = 6, height = 3, name = "PBMC.scRNA.tf")
#'
#'
#' @importFrom ggplot2 aes element_text geom_point ggplot ggsave labs scale_colour_gradient2 theme theme_classic
#' @importFrom ggrepel geom_text_repel
#' @export

VisualizeTFenrichment <- function(TFs = NULL, cluster.1, cluster.2 = NULL, type = "RNA", SeuratObj, visual.topnumber = 10, visual.totalnumber = 100, LISA.table = NULL, GIGGLE.table = NULL, width = 5, height = 4.5, name = "TFEnrichmentPlot"){
  if(type == "RNA")
  {
    if(is.null(LISA.table)) LISA.table = paste0(SeuratObj@project.name,'_lisa.txt')
    TFscore = read.delim(LISA.table, check.names=F)
    sg = intersect(rownames(SeuratObj),rownames(TFscore))
    TFmean =  apply(log2(SeuratObj$RNA@counts[sg,SeuratObj@meta.data[,'seurat_clusters']==as.character(cluster.1)]+1),1,mean)+0.0000000001
    TFmean =  scale((TFmean/abs(TFmean))*(abs(TFmean)^0.3),scale=FALSE)
    TFplot =  cbind(TFmean, TFscore[sg,as.character(cluster.1)])
    TFplot =  TFplot[order(TFplot[,2], decreasing=T),]
    TFplot =  cbind(1:nrow(TFplot),TFplot); colnames(TFplot)<-c("rank","expr","TFscore"); TFplot<-as.data.frame(TFplot)[1:visual.totalnumber,]
    if(is.null(TFs)) {TFplot$plot <- 0;TFplot[TFplot$rank<=visual.topnumber,]$plot <- 1}
    else{TFplot$plot <- 0;TFplot[TFs,]$plot <- 1}

    p <- ggplot(TFplot, aes(x=rank, y=TFscore)) +
    geom_point(aes(color = expr, size = TFscore)) +
    scale_colour_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
    labs(title=paste0("Cluster ",cluster.1," Enriched Regulators"),x="Rank of enriched TFs",y="LISA -log10(pvalue)") +
    geom_text_repel(data = TFplot[TFplot$plot==1,], aes(label = rownames(TFplot[TFplot$plot==1,])),size = 3.5, point.padding = NA, segment.color = "grey50",  segment.size  = 0.1) +
    theme_classic(base_size = 10) + theme(legend.position = "top", plot.title = element_text(size = 12, face = "bold")) 
    ggsave(paste0(name,".pdf"),p, width=width, height=height,useDingbats=FALSE)
  }
  if(type == "ATAC")
  {
    if(is.null(GIGGLE.table)) GIGGLE.table = paste0(SeuratObj@project.name,'_giggle.txt')
    TFscore = read.delim(GIGGLE.table, check.names=F)
    sg = intersect(rownames(SeuratObj$ACTIVITY),rownames(TFscore))
    TFmean = apply(log2(SeuratObj$ACTIVITY@counts[sg,SeuratObj@meta.data[,'seurat_clusters']==as.character(cluster.1)]+1),1,mean)+0.0000000001;
    TFmean = scale((TFmean/abs(TFmean))*(abs(TFmean)^0.3),scale=FALSE)
    TFplot = cbind(TFmean, TFscore[sg,as.character(cluster.1)])
    TFplot = TFplot[order(TFplot[,2], decreasing=T),]
    TFplot = cbind(1:nrow(TFplot),TFplot); colnames(TFplot)<-c("rank","RP","TFscore"); TFplot<-as.data.frame(TFplot)[1:visual.totalnumber,]
    if(is.null(TFs)) {TFplot$plot <- 0;TFplot[TFplot$rank<=visual.topnumber,]$plot <- 1}
    else{TFplot$plot <- 0;TFplot[TFs,]$plot <- 1}

    p <- ggplot(TFplot, aes(x=rank, y=TFscore)) +
    geom_point(aes(color = RP, size = TFscore)) +
    scale_colour_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
    labs(title=paste0("Cluster ",cluster.1," Enriched Regulators"),x="Rank of enriched TFs",y="GIGGLE log10(score)") +
    geom_text_repel(data = TFplot[TFplot$plot==1,], aes(label = rownames(TFplot[TFplot$plot==1,])),size = 3.5, point.padding = NA, segment.color = "grey50",  segment.size  = 0.1) +
    theme_classic(base_size = 10) + theme(legend.position = "top", plot.title = element_text(size = 12, face = "bold")) 
    ggsave(paste0(name,".pdf"),p, width=width, height=height,useDingbats=FALSE)
  }
  if(type == "Integrated")
  {
    if(is.null(LISA.table)) LISA.table = paste0(SeuratObj@project.name,'_lisa.txt')
    if(is.null(GIGGLE.table)) GIGGLE.table = paste0(SeuratObj@project.name,'_giggle.txt')
    TFscore1 = read.delim(LISA.table, check.names=F)
    TFscore2 = read.delim(GIGGLE.table, check.names=F)
    sg = intersect(intersect(rownames(SeuratObj),rownames(TFscore1)),rownames(TFscore2))
    TFmean <- apply(log2(SeuratObj$RNA@counts[sg,SeuratObj@meta.data[,'seurat_clusters']==as.character(cluster.1)]+1),1,mean)+0.0000000001 # expression uing scRNA-seq
    TFmean <- scale((TFmean/abs(TFmean))*(abs(TFmean)^0.3),scale=FALSE)
    TFplot <- cbind(TFmean, TFscore1[sg,as.character(cluster.1)], TFscore2[sg,as.character(cluster.2)])
    TFplot <- TFplot[order(TFplot[,3], decreasing=T),];TFplot <- cbind(1:nrow(TFplot),TFplot) # rank uing scATAC-seq
    TFplot <- TFplot[order(TFplot[,3], decreasing=T),];TFplot <- cbind(1:nrow(TFplot),TFplot) # rank uing scRNA-seq
    TFplot <- cbind(sqrt(TFplot[,1]*TFplot[,2]),TFplot);TFplot <- TFplot[order(TFplot[,1], decreasing=F),];TFplot[,1] <- 1:nrow(TFplot) # rank using rank-product
    colnames(TFplot)<-c("rank","rankLISA","rankGIGGLE","expr","LISA","GIGGLE"); TFplot<-as.data.frame(TFplot)[1:visual.totalnumber,]
    if(is.null(TFs)) {TFplot$plot <- 0;TFplot[TFplot$rank<=visual.topnumber,]$plot <- 1}
    else{TFplot$plot <- 0;TFplot[TFs,]$plot <- 1}

    p <- ggplot(TFplot, aes(x=LISA, y=GIGGLE)) +
    geom_point(aes(color = expr, size = GIGGLE), shape = 19) +
    scale_colour_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
    labs(title=paste0("RNA cluster ",cluster.1," and ATAC cluster ",cluster.2," Enriched Regulators"),x="LISA -log10(pvalue)",y="GIGGLE log10(score)") +
    geom_text_repel(data = TFplot[TFplot$plot==1,], aes(label = rownames(TFplot[TFplot$plot==1,])), size = 3.5, point.padding = NA, segment.color = "grey50",  segment.size  = 0.1) +
    theme_classic(base_size = 10) + theme(legend.position = "top", plot.title = element_text(size = 12, face = "bold")) 
    ggsave(paste0(name,".pdf"),p, width=width, height=height,useDingbats=FALSE)
  }
  return(p)
}



