#' Violin plot to show expression level or regulatory potential of genes
#'
#' Draw a violin plot to show the expression level (RNA) or regulatory potential (ATAC) of given genes in different cell clusters.
#'
#' @docType methods
#' @name VisualizeVlnplot
#' @rdname VisualizeVlnplot
#'
#' @param genes Genes to plot.
#' @param type Type of the dataset. If \code{type} is "RNA", the expression level of genes will be visulized. 
#' If \code{type} is "ATAC", the regulatory potential will be used.
#' @param SeuratObj A Seurat object. If \code{type} is "RNA", \code{SeuratObj} should be the Seurat object generated by \code{\link{RNARunSeurat}} function.
#' If \code{type} is "ATAC", \code{SeuratObj} should be a Seurat object created using RP matrix achievesd from \code{\link{ATACAnnotateCelltype}} function.
#' @param ncol Number of columns by which multiple plots are arranged.
#' @param width Width of the plots.
#' @param height Height of the plots.
#' @param name Output name of the plots. Default is "MultipleVlnPlot".
#'
#' @author Chenfei Wang, Dongqing Sun
#'
#' @return A ggplot object which can be visulaized by \code{link{print}}.
#'
#'
#' @examples
#' data(pbmc.RNA)
#' pbmc <- RNARunSeurat(inputMat = pbmc.RNA, project = "PBMC.scRNA.Seurat")
#' pbmc.tfs <- RNAAnnotateTranscriptionFactor(pbmc$RNA, pbmc$genes, project = "PBMC.scRNA.TF", method = "LISA")
#'
#' # TFs of interest
#' tfs = sapply(pbmc.tfs[[1]], function(x){return(unlist(strsplit(x, split = " | ", fixed = TRUE))[1])})
#' VisualizeVlnplot(genes = tfs, type = "RNA", SeuratObj = pbmc$RNA, ncol = 5, width = 6, height = 3, name = "PBMC.scRNA.tf")
#'
#' # Genes of interest
#' VisualizeVlnplot(genes = c("MS4A1","FCGR3A","CD3D","GZMB"), type = "RNA", SeuratObj = pbmc$RNA, ncol = 2, width = 7, height =4.5, name = "PBMC.scRNA.genes")
#'
#' @importFrom Seurat CombinePlots GetAssayData Idents
#' @importFrom ggplot2 aes element_blank element_text element_line geom_violin ggplot ggsave labs theme
#' @export

VisualizeVlnplot <- function(genes, type, SeuratObj, ncol = NULL, width = 6, height = 4, name = "MultipleVlnPlot"){
  if(type == "ATAC"){
    genes = intersect(rownames(SeuratObj$ACTIVITY),unique(genes))
    gene_expr = GetAssayData(object = SeuratObj$ACTIVITY)[genes, ]
  }
  if(type == "RNA"){
    genes = intersect(rownames(SeuratObj),unique(genes))
    gene_expr = GetAssayData(object = SeuratObj)[genes, ]
  }
  cell_cluster = Idents(SeuratObj)
  vlnplots = lapply(genes, function(x){
    expr_cluster = merge(cell_cluster, as.data.frame(gene_expr[x, ]), by.x = 0, by.y = 0)
    row.names(expr_cluster) = expr_cluster[,1]
    expr_cluster = expr_cluster[,-1]
    colnames(expr_cluster) = c("Cluster","Gene")
    expr_cluster$Cluster = as.factor(expr_cluster$Cluster)
    
    if(type == "RNA"){
      ytitle = "Expression level"}
    if(type == "ATAC"){
      ytitle = "RP score"}
    p = ggplot(expr_cluster, aes(Cluster, Gene)) + 
      geom_violin(aes(fill = Cluster), show.legend = FALSE, scale = "width") + 
      labs(y = ytitle, title = x) +
      theme(axis.text.x = element_text(size = 6), axis.title = element_text(size = 12), axis.text.y = element_text(size = 10), plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"))
    return(p)
  })
  combinedplot = CombinePlots(vlnplots, ncol = ncol)
  ggsave(paste0(name,"_vlnplot.png"), combinedplot,  width=width, height=height)
  return(combinedplot)
}



